name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checkout scripts lib
        uses: actions/checkout@v4
        with:
          repository: serhatbasesgioglu/modulops
          ref: dev
          path: modulops

      - name:
        run: |
          chmod +x modulops/**/*.sh
          modulops/scripts/dotnet.sh dummy-dotnet.csproj Release
          ls -la
